
name: 20NewsGroups
batches_prefix: 20NG
dataset_path: '/data_mil/datasets/20_News_dataset/ /data/datasets/20_News_dataset/20NG_BOW.csv'

word: "@word"

min_num_topics: 10
max_num_topics: 30

num_topics_interval: 3
num_fit_iterations: 40
num_restarts: 6



