
name: Reuters
batches_prefix: Reuters
dataset_path: '/data_mil/datasets/Reuters/Reuters.csv'

word: "@word"

min_num_topics: 5
max_num_topics: 150

num_topics_interval: 5
num_fit_iterations: 40
num_restarts: 3



